echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "We are learning github and git commands"
echo "We are learning git commands"